In [1]:
#This will be exactly same as ForwardPropagation1, but, in this neural network we'll also have a hidden layer having 2 units
# and a bias unit(1).
#Thus, the no. of weights b/w i/p and hidden layer will be 3*2 = 6, and b/w hidden layer and o/p layer will be 3*1 = 3 

In [2]:
#We'll reuse the same code from ForwardPropagation1, and we'll add more code to it to get the code for implementing our current
#required neural network.

In [3]:
import numpy as np

In [4]:
#AND dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) #X1 and X2
Y = np.array([[0, 0, 0, 1]]).T #Y 

In [5]:
#sigmoid function for the single unit in the o/p unit
def sig(z):
    return 1/(1 + np.exp(-z))

In [6]:
#No hidden layer weights! (bcoz same code from ForwardPropagation1)
weights = 2 * np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[0.80129752],
        [0.03850659]]),
 array([0.63497771]))

In [7]:
#Forward propagation w/o hidden layer (bcoz same code from ForwardPropagation1)
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.65361729],
       [0.66228291],
       [0.80787719],
       [0.81378311]])

In [8]:
#Now, we're done with copying the ForwardPropagation1 code.
#Now's the time to get the hidden layer having a bias unit and 2 units implementing the sigmoid function
#Also, we need to add some weights, as now, we have 3*2 = 6 weights for hidden layer(i.e. weights b/w i/p and hidden), and 
#we have 3*1 = 3 weights for o/p layer(i.e. weights b/w hidden and o/p).

In [9]:
wh = 2 * np.random.random((2, 2)) - 1 #hidden layer weights (b/w i/p and hidden)
bh = 2 * np.random.random((1, 2)) - 1 #hidden layer bias weights (b/w i/p and hidden)
wo = 2 * np.random.random((2, 1)) - 1 #o/p layer weights (b/w hidden and o/p)
bo = 2 * np.random.random((1, 1)) - 1 #o/p layer bias weights (b/w hidden and o/p)

In [10]:
#Now, that we have initialized all the required weights, we can implement forward propagation for our current neural network!

In [11]:
output0 = X 
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[0.56770945],
       [0.5432162 ],
       [0.53872046],
       [0.51375096]])

In [12]:
#Thus, we have successfully implemented forward propagation for a neural network having a single hidden layer.