In [1]:
#Forward propagation for a simple neural network which we will build from scratch, which has just an i/p layer containing a 
#bias and X1 and X2, and an o/p layer having a single unit which has  a sigmoid function. We will use the AND dataset.

In [2]:
import numpy as np

In [3]:
#AND dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) #X1 and X2
Y = np.array([0, 0, 0, 1]) #Y 

In [4]:
#We need to convert our Y into a 2D array and then transpose it because, as it is 1D array it looks like:
#[0, 0, 0, 1] whereas X is like:
#[[0, 0],
#[0, 1],
#[1, 0],
#[1, 1]]
#So, Y should be like:
#[[0],
#[0],
#[0],
#[1]]
Y = np.array([[0, 0, 0, 1]])
#now Y looks like:
#[[0, 0, 0, 1]]
#Thus, we need to do transpose, to get desirable Y
Y = np.array([[0, 0, 0, 1]]).T

In [5]:
X, Y #perfect dataset!

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [0],
        [0],
        [1]]))

In [6]:
#sigmoid function for the single unit in the o/p unit
def sig(z):
    return 1/(1 + np.exp(-z))

In [7]:
#Now let's initialize our weights (random weights, we'll correct them using backpropagation later.)
#We'll keep them a bit generic
#We'll use the np.random.random() as it will generate random values for our weights in the dimension which we want(i.e. the
#dimension that suits our dataset -> (2, 1) -> (2 rows, 1 column), thus, giving us two weights w1 and w2, for X1 and X2,
#respecively).
weights = np.random.random((2, 1))
weights

array([[0.68618963],
       [0.87205669]])

In [9]:
#right now, the random weights are being genrated within the range of  0 to 1.
#But, then we won't have any random weights.
#So, to get them in a range of -1 to 1, we just multiply our current range with 2, so it becomes 0 to 2, and then we subrtract
#1 from it, so the range moves 1 space back, and we get -1 to 1
#Similarly, let's also get our bias. In this problem, we're having  only single  bias, but that won't always be the case.
weights = 2 * np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[ 0.81515584],
        [-0.35005123]]),
 array([-0.79287428]))

In [10]:
#Thus, we have all our required weights initialized.
#Now's the time to write the code for forward propagation.

In [12]:
#We know that the output of the i/p layer is the i/p itself, here X
output0 = X

#In our current e.g. we don't have any hidden layers, directly an o/p layer with a single unit which implements sigmoid function
#In order to get z (= WX + B = w1x1 + w2x2 + b), we won't be multiplying each x to its corresponding weight, but we'll use
#dot product of 'output0' and 'weights'.
output = sig(np.dot(output0, weights) + bias)
output

array([[0.31155184],
       [0.24178364],
       [0.50557016],
       [0.41878339]])

In [13]:
#Thus, we have successfully implemented forward propagation. But, this was a simple neural network with no hidden layers.