In [1]:
import numpy as np

In [2]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0, 1, 1, 0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(z))

In [4]:
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [5]:
#one hidden layer weights
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1
lr = 0.1

In [6]:
#copy-pasted weight updation code from no hidden layer n
# for iter in range(10000):
    
#     output0 = X
#     output = sig(np.dot(output0, weights) + bias)

    
#     first_term = output - Y #d(E)/d(Oj) = y_pred - y_actual
#     input_for_last_layer = np.dot(output0, weights) + bias #i/p_j
#     second_term = derivative_sig(input_for_last_layer) #d(Oj)/d(i/p_j) = sig(z)(1 - sig(z))
#     first_two = first_term * second_term
    
#     changes = np.dot(output0.T, first_two)
#     weights = weights - lr * changes
    
#     bias_change = np.sum(first_two)
#     bias = bias - lr * bias_change
    
# output = sig(np.dot(X, weights) + bias)
# weights, bias, output

In [10]:
#forward propagation with one hidden layer
for iter in range(1000):
    output0 = X
    inputHidden = np.dot(output0, wh) + bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden, wo) + bo 
    output = sig(inputForOutputLayer)

    first_term_output_layer = output - Y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer * second_term_output_layer

    #Backpropagating first_two_output_layer into hidden layer
    first_term_hidden_layer = np.dot(first_two_output_layer, wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    #from above cell you'll notice that to get the changes for the a layer we need to do dot product of current layer's first_two  with previous layer's o/p
    changes_output = np.dot(outputHidden.T, first_two_output_layer)
    #from above cell you'll notice that to get the bias_changes for the layer we need to sum the first_two of that layer
    changes_output_bias = np.sum(first_two_output_layer, axis = 0, keepdims = True) #we also have to use parameter keepdims = True i.e. keep dimension, so that it maintains its dimensions as a vector instead of giving the sum simply as a single value, thus, we can do vector addition with the bias else it wouldn't be possible. Also, we use axis = 0 to specify in which axis it has to do addition

    changes_hidden = np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis = 0, keepdims = True)

    #now let's do the actual changes
    wo = wo - lr * changes_output
    bo = bo - lr * changes_output_bias

    wh = wh - lr * changes_hidden
    bh = bh - lr * changes_hidden_bias
    
#Getting output again after updating weights optimally
output0 = X
inputHidden = np.dot(output0, wh) + bh
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden, wo) + bo 
output = sig(inputForOutputLayer)
output, wh, bh, wo, bo

(array([[0.00285849],
        [0.00273478],
        [0.00325913],
        [0.0032266 ]]),
 array([[ 0.70203961,  0.04272399],
        [-0.5109873 ,  0.16277069]]),
 array([[1.15534798, 1.2030535 ]]),
 array([[1.08029964],
        [2.48908394]]),
 array([[5.02104224]]))

In [11]:
#We have got the desired o/p. And if you use all these values and do manual calculation you'll notice that we have got the 
#units working in the same manner as we did in the initial lectures where we did XOR neural network by hand.
#It's possible that if you run all this again, you might get different functions in the units, but the final o/p will be 
#almost same!

In [12]:
#Thus, we have successfully implemented a neural network having a hidden layer!